# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fasttunnel < Formula
  desc "Open-source tunneling — expose local services to the internet instantly."
  homepage "https://fasttunnel.dev"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fasttunnels/fasttunnel/releases/download/v0.2.0/fasttunnel_0.2.0_darwin_amd64.tar.gz"
      sha256 "1543f3a2539e6ffd357e57876e0885dbd643f6a97cac18b57923df1b11190fc9"

      define_method(:install) do
        bin.install "fasttunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fasttunnels/fasttunnel/releases/download/v0.2.0/fasttunnel_0.2.0_darwin_arm64.tar.gz"
      sha256 "06014ba5aa92aa2024660662f734af2499eb7cc892caf6bc84f4ef5533a0ebc5"

      define_method(:install) do
        bin.install "fasttunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fasttunnels/fasttunnel/releases/download/v0.2.0/fasttunnel_0.2.0_linux_amd64.tar.gz"
      sha256 "145656bde3552abbee082be19ca7168d224a451bed344e26d6e0272e1366aaff"
      define_method(:install) do
        bin.install "fasttunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fasttunnels/fasttunnel/releases/download/v0.2.0/fasttunnel_0.2.0_linux_arm64.tar.gz"
      sha256 "c0ed5bbbe7e8ac96595c248eb2243c9592815fae0ed430f8f42ccec669403050"
      define_method(:install) do
        bin.install "fasttunnel"
      end
    end
  end

  test do
    system "#{bin}/fasttunnel --version"
  end
end
