# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fasttunnel < Formula
  desc "Open-source tunneling — expose local services to the internet instantly."
  homepage "https://fasttunnel.dev"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fasttunnels/fasttunnel/releases/download/v0.1.3/fasttunnel_0.1.3_darwin_amd64.tar.gz"
      sha256 "b9c7ae31fdfeddbba7ed405b930e83a55a797e7b252a31b9d2342cc9355da6e0"

      define_method(:install) do
        bin.install "fasttunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fasttunnels/fasttunnel/releases/download/v0.1.3/fasttunnel_0.1.3_darwin_arm64.tar.gz"
      sha256 "cde94c7b5d669e942252119f65d6463ae5da6f54e7303f7bd167d1ecc68b7566"

      define_method(:install) do
        bin.install "fasttunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fasttunnels/fasttunnel/releases/download/v0.1.3/fasttunnel_0.1.3_linux_amd64.tar.gz"
      sha256 "5759d8672e2377bd407633c82d63d3761c0f7bdb237ae4e445a2f07c4220f21b"
      define_method(:install) do
        bin.install "fasttunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fasttunnels/fasttunnel/releases/download/v0.1.3/fasttunnel_0.1.3_linux_arm64.tar.gz"
      sha256 "4b49105c65f798ac68ed8c221d92462e16aeb9a87339dc641c8a854d968e3884"
      define_method(:install) do
        bin.install "fasttunnel"
      end
    end
  end

  test do
    system "#{bin}/fasttunnel --version"
  end
end
